### PR TITLE
Use Unraid own Dashboard box like APCUPSD

### PR DESCRIPTION
**Pull request by gfjardim**

### CODE REVIEW

**Comment by dmacias72** [comment]
Thanks. I had worked on this a bit but never got around to finishing it.

**Comment by gfjardim** [comment]
Thanks, I'm still figuring out how NUT and this plugin works. THat's why I'm sending all of these PR.

One thing that I noticed is that, in my case, battery.runtime is a growing integer that reflects how many seconds the system is running on battery. Apparently, to check how many seconds left in battery mode, I have tu pull this data from battery.runtime.low, which is on par with this: https://networkupstools.org/docs/user-manual.chunked/apcs01.html

Is there a problem to add a select box in config to let users choose it instead of hardcode it?

**Comment by dmacias72** [comment]
I appreciate the help. I haven't had much time the past couple years.

The selection for battery runtime is a good idea. 

Now if I can get you to head over to the nut repo and fix their libusb issues 😁. The branch I have compiled right now works but floods my log with io errors. But at least it stays connected. Idk maybe they are fixed. I'm gonna compile a newer version and see.

**Comment by gfjardim** [comment]
Which driver your UPS uses?

**Comment by dmacias72** [comment]
usbhid driver. Its a Tripplite 1200. The plugin uses nut compiled on the libusb 1.0+0.1 branch.  I might try the usb compatible. It has some newer fixes

**Pull request merged**
